Fix CI failures: use kernel mirror and fix volatile syntax issue in sbase
1. Updated kernel download URL in `build_iso.sh` and `repo/linux-headers/sources` to `mirrors.kernel.org` because `cdn.kernel.org` was failing to connect due to timeout.
2. The compilation of `sbase` failed using `cproc` due to `make/main.c:94:14: error: volatile store is not yet supported`. Fixed this by adding a `sed` command in `repo/sbase/build` to remove `volatile` from `sig_atomic_t` before compilation.

Co-authored-by: qvkap <293183705+qvkap@users.noreply.github.com>